// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.groups;

import edu.uoc.lti.ContentTypeable;

/**
 * @author Created by xaracil@uoc.edu
 */
public enum ContentTypes implements ContentTypeable {
	GROUP("application", "vnd.ims.lti-gs.v1.contextgroupcontainer+json"), SET("application", "application/vnd.ims.lti-gs.v1.contextgroupsetcontainer+json");
	private final String type;
	private final String subtype;

	@java.lang.SuppressWarnings("all")
	private ContentTypes(final String type, final String subtype) {
		this.type = type;
		this.subtype = subtype;
	}

	@java.lang.SuppressWarnings("all")
	public String getType() {
		return this.type;
	}

	@java.lang.SuppressWarnings("all")
	public String getSubtype() {
		return this.subtype;
	}
}
