// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.groups;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Universitat Oberta de Catalunya
 * Made for the project lti-13-core
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Group {
	/**
	 * The unique identifier for the context group. This identifier must be unique within all context groups for the current context and MUST remain stable between requests.
	 */
	private String id;
	/**
	 * The human readable name for the context group. The tool MAY use this value to display to end users.
	 */
	private String name;
	/**
	 * A string value identifying the purpose of that group.
	 */
	private String tag;
	/**
	 * The id of the set that group belongs to.
	 */
	@JsonProperty("set_id")
	private String setId;

	/**
	 * The unique identifier for the context group. This identifier must be unique within all context groups for the current context and MUST remain stable between requests.
	 */
	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	/**
	 * The human readable name for the context group. The tool MAY use this value to display to end users.
	 */
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	/**
	 * A string value identifying the purpose of that group.
	 */
	@java.lang.SuppressWarnings("all")
	public String getTag() {
		return this.tag;
	}

	/**
	 * The id of the set that group belongs to.
	 */
	@java.lang.SuppressWarnings("all")
	public String getSetId() {
		return this.setId;
	}

	/**
	 * The unique identifier for the context group. This identifier must be unique within all context groups for the current context and MUST remain stable between requests.
	 */
	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	/**
	 * The human readable name for the context group. The tool MAY use this value to display to end users.
	 */
	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}

	/**
	 * A string value identifying the purpose of that group.
	 */
	@java.lang.SuppressWarnings("all")
	public void setTag(final String tag) {
		this.tag = tag;
	}

	/**
	 * The id of the set that group belongs to.
	 */
	@JsonProperty("set_id")
	@java.lang.SuppressWarnings("all")
	public void setSetId(final String setId) {
		this.setId = setId;
	}
}
