// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.groups;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Universitat Oberta de Catalunya
 * Made for the project lti-13-core
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class GroupSet {
	/**
	 * The unique identifier for the context group set. This identifier must be unique within all context group sets for the current context and MUST remain stable between requests.
	 */
	private String id;
	/**
	 * The human readable name for the context group set. The tool MAY use this value to display to end users.
	 */
	private String name;

	/**
	 * The unique identifier for the context group set. This identifier must be unique within all context group sets for the current context and MUST remain stable between requests.
	 */
	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	/**
	 * The human readable name for the context group set. The tool MAY use this value to display to end users.
	 */
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	/**
	 * The unique identifier for the context group set. This identifier must be unique within all context group sets for the current context and MUST remain stable between requests.
	 */
	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	/**
	 * The human readable name for the context group set. The tool MAY use this value to display to end users.
	 */
	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}
}
