// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.ags;

/**
 * @author Created by xaracil@uoc.edu
 */
public enum ActivityProgressEnum {
	INITIALIZED("Initialized"), STARTED("Started"), IN_PROGRESS("InProgress"), SUBMITTED("Submitted"), COMPLETED("Completed");
	private final String value;

	@java.lang.SuppressWarnings("all")
	private ActivityProgressEnum(final String value) {
		this.value = value;
	}

	@java.lang.SuppressWarnings("all")
	public String getValue() {
		return this.value;
	}
}
