// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.ags;

import edu.uoc.lti.ContentTypeable;

/**
 * @author Created by xaracil@uoc.edu
 */
public enum ContentTypes implements ContentTypeable {
	LINE_ITEM("application", "vnd.ims.lis.v2.lineitem+json"), LINE_ITEM_CONTAINER("application", "vnd.ims.lis.v2.lineitemcontainer+json"), RESULT("application", "vnd.ims.lis.v2.resultcontainer+json"), SCORE("application", "vnd.ims.lis.v1.score+json");
	private final String type;
	private final String subtype;

	@java.lang.SuppressWarnings("all")
	private ContentTypes(final String type, final String subtype) {
		this.type = type;
		this.subtype = subtype;
	}

	@java.lang.SuppressWarnings("all")
	public String getType() {
		return this.type;
	}

	@java.lang.SuppressWarnings("all")
	public String getSubtype() {
		return this.subtype;
	}
}
