// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.ags;

/**
 * @author Created by xaracil@uoc.edu
 */
public enum GradingProgressEnum {
	NOT_READY("NotReady"), FAILED("Failed"), PENDING("Pending"), PENDING_MANUAL("PendingManual"), FULLY_GRADED("FullyGraded");
	private final String value;

	@java.lang.SuppressWarnings("all")
	public String getValue() {
		return this.value;
	}

	@java.lang.SuppressWarnings("all")
	private GradingProgressEnum(final String value) {
		this.value = value;
	}
}
