// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.ags;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.time.Instant;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Submission {
	/**
	 * Date and time in ISO 8601 format when a submission can start being submitted by learner
	 */
	private Instant startDateTime;

	public String getStartDateTime() {
		return startDateTime != null ? startDateTime.toString() : null;
	}

	/**
	 * Date and time in ISO 8601 format when a submission can last be submitted by learner
	 */
	private Instant endDateTime;

	public String getEndDateTime() {
		return endDateTime != null ? endDateTime.toString() : null;
	}

	/**
	 * Date and time in ISO 8601 format when a submission can start being submitted by learner
	 */
	@java.lang.SuppressWarnings("all")
	public void setStartDateTime(final Instant startDateTime) {
		this.startDateTime = startDateTime;
	}

	/**
	 * Date and time in ISO 8601 format when a submission can last be submitted by learner
	 */
	@java.lang.SuppressWarnings("all")
	public void setEndDateTime(final Instant endDateTime) {
		this.endDateTime = endDateTime;
	}
}
