// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

/**
 * @author Created by xaracil@uoc.edu
 */
public class Custom {
	private String quiz_id;
	private String duedate;

	@java.lang.SuppressWarnings("all")
	Custom(final String quiz_id, final String duedate) {
		this.quiz_id = quiz_id;
		this.duedate = duedate;
	}


	@java.lang.SuppressWarnings("all")
	public static class CustomBuilder {
		@java.lang.SuppressWarnings("all")
		private String quiz_id;
		@java.lang.SuppressWarnings("all")
		private String duedate;

		@java.lang.SuppressWarnings("all")
		CustomBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Custom.CustomBuilder quiz_id(final String quiz_id) {
			this.quiz_id = quiz_id;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Custom.CustomBuilder duedate(final String duedate) {
			this.duedate = duedate;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Custom build() {
			return new Custom(this.quiz_id, this.duedate);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Custom.CustomBuilder(quiz_id=" + this.quiz_id + ", duedate=" + this.duedate + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Custom.CustomBuilder builder() {
		return new Custom.CustomBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getQuiz_id() {
		return this.quiz_id;
	}

	@java.lang.SuppressWarnings("all")
	public String getDuedate() {
		return this.duedate;
	}

	@java.lang.SuppressWarnings("all")
	public void setQuiz_id(final String quiz_id) {
		this.quiz_id = quiz_id;
	}

	@java.lang.SuppressWarnings("all")
	public void setDuedate(final String duedate) {
		this.duedate = duedate;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Custom(quiz_id=" + this.getQuiz_id() + ", duedate=" + this.getDuedate() + ")";
	}
}
