// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class DataItem extends Item {
	private String data;

	public DataItem(String type, String data) {
		super(type);
		this.data = data;
	}


	@java.lang.SuppressWarnings("all")
	public static class DataItemBuilder {
		@java.lang.SuppressWarnings("all")
		private String type;
		@java.lang.SuppressWarnings("all")
		private String data;

		@java.lang.SuppressWarnings("all")
		DataItemBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public DataItem.DataItemBuilder type(final String type) {
			this.type = type;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public DataItem.DataItemBuilder data(final String data) {
			this.data = data;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public DataItem build() {
			return new DataItem(this.type, this.data);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "DataItem.DataItemBuilder(type=" + this.type + ", data=" + this.data + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static DataItem.DataItemBuilder builder() {
		return new DataItem.DataItemBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	public void setData(final String data) {
		this.data = data;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "DataItem(super=" + super.toString() + ", data=" + this.getData() + ")";
	}
}
