// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

/**
 * @author Created by xaracil@uoc.edu
 */
public enum DocumentTargetEnum {
  frame, iframe, window;

  @java.lang.SuppressWarnings("all")
  private DocumentTargetEnum() {
  }
}
