// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.time.Instant;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Duration {
	private Instant startDate;
	private Instant endDate;

	public String getStartDateTime() {
		return startDate != null ? startDate.toString() : null;
	}

	public String getEndDateTime() {
		return endDate != null ? endDate.toString() : null;
	}

	@java.lang.SuppressWarnings("all")
	Duration(final Instant startDate, final Instant endDate) {
		this.startDate = startDate;
		this.endDate = endDate;
	}


	@java.lang.SuppressWarnings("all")
	public static class DurationBuilder {
		@java.lang.SuppressWarnings("all")
		private Instant startDate;
		@java.lang.SuppressWarnings("all")
		private Instant endDate;

		@java.lang.SuppressWarnings("all")
		DurationBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Duration.DurationBuilder startDate(final Instant startDate) {
			this.startDate = startDate;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Duration.DurationBuilder endDate(final Instant endDate) {
			this.endDate = endDate;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Duration build() {
			return new Duration(this.startDate, this.endDate);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Duration.DurationBuilder(startDate=" + this.startDate + ", endDate=" + this.endDate + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Duration.DurationBuilder builder() {
		return new Duration.DurationBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public void setStartDate(final Instant startDate) {
		this.startDate = startDate;
	}

	@java.lang.SuppressWarnings("all")
	public void setEndDate(final Instant endDate) {
		this.endDate = endDate;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Duration(startDate=" + this.startDate + ", endDate=" + this.endDate + ")";
	}
}
