// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

/**
 * @author Created by xaracil@uoc.edu
 */
public class Embed {
	private final String html;

	@java.lang.SuppressWarnings("all")
	Embed(final String html) {
		this.html = html;
	}


	@java.lang.SuppressWarnings("all")
	public static class EmbedBuilder {
		@java.lang.SuppressWarnings("all")
		private String html;

		@java.lang.SuppressWarnings("all")
		EmbedBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Embed.EmbedBuilder html(final String html) {
			this.html = html;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Embed build() {
			return new Embed(this.html);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Embed.EmbedBuilder(html=" + this.html + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Embed.EmbedBuilder builder() {
		return new Embed.EmbedBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getHtml() {
		return this.html;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Embed(html=" + this.getHtml() + ")";
	}
}
