// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class HtmlItem extends Item {
	private static String TYPE = "html";
	/**
	 * HTML fragment to be embedded. The platform is expected to sanitize it against cross-site scripting attacks.
	 */
	private final String html;
	/**
	 * String, plain text to use as the title or heading for content.
	 */
	private String title;
	/**
	 * String, plain text description of the content item intended to be displayed to all users who can access the item.
	 */
	private String text;

	public HtmlItem(String html) {
		super(TYPE);
		this.html = html;
	}

	public HtmlItem(String html, String title, String text) {
		this(html);
		this.title = title;
		this.text = text;
	}


	@java.lang.SuppressWarnings("all")
	public static class HtmlItemBuilder {
		@java.lang.SuppressWarnings("all")
		private String html;
		@java.lang.SuppressWarnings("all")
		private String title;
		@java.lang.SuppressWarnings("all")
		private String text;

		@java.lang.SuppressWarnings("all")
		HtmlItemBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public HtmlItem.HtmlItemBuilder html(final String html) {
			this.html = html;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public HtmlItem.HtmlItemBuilder title(final String title) {
			this.title = title;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public HtmlItem.HtmlItemBuilder text(final String text) {
			this.text = text;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public HtmlItem build() {
			return new HtmlItem(this.html, this.title, this.text);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "HtmlItem.HtmlItemBuilder(html=" + this.html + ", title=" + this.title + ", text=" + this.text + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static HtmlItem.HtmlItemBuilder builder() {
		return new HtmlItem.HtmlItemBuilder();
	}

	/**
	 * HTML fragment to be embedded. The platform is expected to sanitize it against cross-site scripting attacks.
	 */
	@java.lang.SuppressWarnings("all")
	public String getHtml() {
		return this.html;
	}

	/**
	 * String, plain text to use as the title or heading for content.
	 */
	@java.lang.SuppressWarnings("all")
	public String getTitle() {
		return this.title;
	}

	/**
	 * String, plain text description of the content item intended to be displayed to all users who can access the item.
	 */
	@java.lang.SuppressWarnings("all")
	public String getText() {
		return this.text;
	}

	/**
	 * String, plain text to use as the title or heading for content.
	 */
	@java.lang.SuppressWarnings("all")
	public void setTitle(final String title) {
		this.title = title;
	}

	/**
	 * String, plain text description of the content item intended to be displayed to all users who can access the item.
	 */
	@java.lang.SuppressWarnings("all")
	public void setText(final String text) {
		this.text = text;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "HtmlItem(super=" + super.toString() + ", html=" + this.getHtml() + ", title=" + this.getTitle() + ", text=" + this.getText() + ")";
	}
}
