// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Image {
	private final String url;
	private int width;
	private int height;

	@java.lang.SuppressWarnings("all")
	Image(final String url, final int width, final int height) {
		this.url = url;
		this.width = width;
		this.height = height;
	}


	@java.lang.SuppressWarnings("all")
	public static class ImageBuilder {
		@java.lang.SuppressWarnings("all")
		private String url;
		@java.lang.SuppressWarnings("all")
		private int width;
		@java.lang.SuppressWarnings("all")
		private int height;

		@java.lang.SuppressWarnings("all")
		ImageBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Image.ImageBuilder url(final String url) {
			this.url = url;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Image.ImageBuilder width(final int width) {
			this.width = width;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Image.ImageBuilder height(final int height) {
			this.height = height;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Image build() {
			return new Image(this.url, this.width, this.height);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Image.ImageBuilder(url=" + this.url + ", width=" + this.width + ", height=" + this.height + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Image.ImageBuilder builder() {
		return new Image.ImageBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getUrl() {
		return this.url;
	}

	@java.lang.SuppressWarnings("all")
	public int getWidth() {
		return this.width;
	}

	@java.lang.SuppressWarnings("all")
	public int getHeight() {
		return this.height;
	}

	@java.lang.SuppressWarnings("all")
	public void setWidth(final int width) {
		this.width = width;
	}

	@java.lang.SuppressWarnings("all")
	public void setHeight(final int height) {
		this.height = height;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Image(url=" + this.getUrl() + ", width=" + this.getWidth() + ", height=" + this.getHeight() + ")";
	}
}
