// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.HashMap;
import java.util.Map;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public abstract class Item {
	private final String type;
	// extending a type https://www.imsglobal.org/spec/lti-dl/v2p0#extending-a-type
	// gotten from http://tutorials.jenkov.com/java-json/jackson-annotations.html
	private Map<String, Object> properties = new HashMap<>();

	@JsonAnyGetter
	public Map<String, Object> getProperties() {
		return properties;
	}

	@JsonAnySetter
	public void set(String fieldName, Object value) {
		this.properties.put(fieldName, value);
	}

	public Object get(String fieldName) {
		return this.properties.get(fieldName);
	}

	@java.lang.SuppressWarnings("all")
	public Item(final String type) {
		this.type = type;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Item(type=" + this.getType() + ", properties=" + this.getProperties() + ")";
	}

	@java.lang.SuppressWarnings("all")
	public String getType() {
		return this.type;
	}
}
