// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class LineItem {
	/**
	 * Positive decimal value indicating the maximum score possible for this activity
	 */
	private final double scoreMaximum;
	/**
	 * label for the line item. If not present, the title of the content item must be used.
	 */
	private String label;
	/**
	 * String, tool provided ID for the resource.
	 */
	private String resourceId;
	/**
	 * String, additional information about the line item; may be used by the tool to identify line items attached
	 *  to the same resource or resource link (example: grade, originality, participation).
	 */
	private String tag;

	@java.lang.SuppressWarnings("all")
	LineItem(final double scoreMaximum, final String label, final String resourceId, final String tag) {
		this.scoreMaximum = scoreMaximum;
		this.label = label;
		this.resourceId = resourceId;
		this.tag = tag;
	}


	@java.lang.SuppressWarnings("all")
	public static class LineItemBuilder {
		@java.lang.SuppressWarnings("all")
		private double scoreMaximum;
		@java.lang.SuppressWarnings("all")
		private String label;
		@java.lang.SuppressWarnings("all")
		private String resourceId;
		@java.lang.SuppressWarnings("all")
		private String tag;

		@java.lang.SuppressWarnings("all")
		LineItemBuilder() {
		}

		/**
		 * Positive decimal value indicating the maximum score possible for this activity
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LineItem.LineItemBuilder scoreMaximum(final double scoreMaximum) {
			this.scoreMaximum = scoreMaximum;
			return this;
		}

		/**
		 * label for the line item. If not present, the title of the content item must be used.
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LineItem.LineItemBuilder label(final String label) {
			this.label = label;
			return this;
		}

		/**
		 * String, tool provided ID for the resource.
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LineItem.LineItemBuilder resourceId(final String resourceId) {
			this.resourceId = resourceId;
			return this;
		}

		/**
		 * String, additional information about the line item; may be used by the tool to identify line items attached
		 *  to the same resource or resource link (example: grade, originality, participation).
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LineItem.LineItemBuilder tag(final String tag) {
			this.tag = tag;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public LineItem build() {
			return new LineItem(this.scoreMaximum, this.label, this.resourceId, this.tag);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "LineItem.LineItemBuilder(scoreMaximum=" + this.scoreMaximum + ", label=" + this.label + ", resourceId=" + this.resourceId + ", tag=" + this.tag + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static LineItem.LineItemBuilder builder() {
		return new LineItem.LineItemBuilder();
	}

	/**
	 * Positive decimal value indicating the maximum score possible for this activity
	 */
	@java.lang.SuppressWarnings("all")
	public double getScoreMaximum() {
		return this.scoreMaximum;
	}

	/**
	 * label for the line item. If not present, the title of the content item must be used.
	 */
	@java.lang.SuppressWarnings("all")
	public String getLabel() {
		return this.label;
	}

	/**
	 * String, tool provided ID for the resource.
	 */
	@java.lang.SuppressWarnings("all")
	public String getResourceId() {
		return this.resourceId;
	}

	/**
	 * String, additional information about the line item; may be used by the tool to identify line items attached
	 *  to the same resource or resource link (example: grade, originality, participation).
	 */
	@java.lang.SuppressWarnings("all")
	public String getTag() {
		return this.tag;
	}

	/**
	 * label for the line item. If not present, the title of the content item must be used.
	 */
	@java.lang.SuppressWarnings("all")
	public void setLabel(final String label) {
		this.label = label;
	}

	/**
	 * String, tool provided ID for the resource.
	 */
	@java.lang.SuppressWarnings("all")
	public void setResourceId(final String resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * String, additional information about the line item; may be used by the tool to identify line items attached
	 *  to the same resource or resource link (example: grade, originality, participation).
	 */
	@java.lang.SuppressWarnings("all")
	public void setTag(final String tag) {
		this.tag = tag;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "LineItem(super=" + super.toString() + ", scoreMaximum=" + this.getScoreMaximum() + ", label=" + this.getLabel() + ", resourceId=" + this.getResourceId() + ", tag=" + this.getTag() + ")";
	}
}
