// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class LinkItem extends Item {
	private static String TYPE = "link";
	private String title;
	private String text;
	private final String url;
	private Image icon;
	private Image thumbnail;
	private Window window;
	private IFrame iframe;
	private Embed embed;

	public LinkItem(String url) {
		super(TYPE);
		this.url = url;
	}

	public LinkItem(String title, String url, String text, Image icon, Image thumbnail) {
		this(url);
		this.title = title;
		this.text = text;
		this.icon = icon;
		this.thumbnail = thumbnail;
	}


	@java.lang.SuppressWarnings("all")
	public static class LinkItemBuilder {
		@java.lang.SuppressWarnings("all")
		private String title;
		@java.lang.SuppressWarnings("all")
		private String url;
		@java.lang.SuppressWarnings("all")
		private String text;
		@java.lang.SuppressWarnings("all")
		private Image icon;
		@java.lang.SuppressWarnings("all")
		private Image thumbnail;

		@java.lang.SuppressWarnings("all")
		LinkItemBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LinkItem.LinkItemBuilder title(final String title) {
			this.title = title;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LinkItem.LinkItemBuilder url(final String url) {
			this.url = url;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LinkItem.LinkItemBuilder text(final String text) {
			this.text = text;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LinkItem.LinkItemBuilder icon(final Image icon) {
			this.icon = icon;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public LinkItem.LinkItemBuilder thumbnail(final Image thumbnail) {
			this.thumbnail = thumbnail;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public LinkItem build() {
			return new LinkItem(this.title, this.url, this.text, this.icon, this.thumbnail);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "LinkItem.LinkItemBuilder(title=" + this.title + ", url=" + this.url + ", text=" + this.text + ", icon=" + this.icon + ", thumbnail=" + this.thumbnail + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static LinkItem.LinkItemBuilder builder() {
		return new LinkItem.LinkItemBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getTitle() {
		return this.title;
	}

	@java.lang.SuppressWarnings("all")
	public String getText() {
		return this.text;
	}

	@java.lang.SuppressWarnings("all")
	public String getUrl() {
		return this.url;
	}

	@java.lang.SuppressWarnings("all")
	public Image getIcon() {
		return this.icon;
	}

	@java.lang.SuppressWarnings("all")
	public Image getThumbnail() {
		return this.thumbnail;
	}

	@java.lang.SuppressWarnings("all")
	public Window getWindow() {
		return this.window;
	}

	@java.lang.SuppressWarnings("all")
	public IFrame getIframe() {
		return this.iframe;
	}

	@java.lang.SuppressWarnings("all")
	public Embed getEmbed() {
		return this.embed;
	}

	@java.lang.SuppressWarnings("all")
	public void setTitle(final String title) {
		this.title = title;
	}

	@java.lang.SuppressWarnings("all")
	public void setText(final String text) {
		this.text = text;
	}

	@java.lang.SuppressWarnings("all")
	public void setIcon(final Image icon) {
		this.icon = icon;
	}

	@java.lang.SuppressWarnings("all")
	public void setThumbnail(final Image thumbnail) {
		this.thumbnail = thumbnail;
	}

	@java.lang.SuppressWarnings("all")
	public void setWindow(final Window window) {
		this.window = window;
	}

	@java.lang.SuppressWarnings("all")
	public void setIframe(final IFrame iframe) {
		this.iframe = iframe;
	}

	@java.lang.SuppressWarnings("all")
	public void setEmbed(final Embed embed) {
		this.embed = embed;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "LinkItem(super=" + super.toString() + ", title=" + this.getTitle() + ", text=" + this.getText() + ", url=" + this.getUrl() + ", icon=" + this.getIcon() + ", thumbnail=" + this.getThumbnail() + ", window=" + this.getWindow() + ", iframe=" + this.getIframe() + ", embed=" + this.getEmbed() + ")";
	}
}
