// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Presentation {
	@JsonProperty("document_target")
	private String documentTarget;
	private int width;
	private int height;
	@JsonProperty("return_url")
	private String returnUrl;
	@JsonProperty("locale")
	private String locale;


	@java.lang.SuppressWarnings("all")
	public static class PresentationBuilder {
		@java.lang.SuppressWarnings("all")
		private String documentTarget;
		@java.lang.SuppressWarnings("all")
		private int width;
		@java.lang.SuppressWarnings("all")
		private int height;
		@java.lang.SuppressWarnings("all")
		private String returnUrl;
		@java.lang.SuppressWarnings("all")
		private String locale;

		@java.lang.SuppressWarnings("all")
		PresentationBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@JsonProperty("document_target")
		@java.lang.SuppressWarnings("all")
		public Presentation.PresentationBuilder documentTarget(final String documentTarget) {
			this.documentTarget = documentTarget;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Presentation.PresentationBuilder width(final int width) {
			this.width = width;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Presentation.PresentationBuilder height(final int height) {
			this.height = height;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@JsonProperty("return_url")
		@java.lang.SuppressWarnings("all")
		public Presentation.PresentationBuilder returnUrl(final String returnUrl) {
			this.returnUrl = returnUrl;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@JsonProperty("locale")
		@java.lang.SuppressWarnings("all")
		public Presentation.PresentationBuilder locale(final String locale) {
			this.locale = locale;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Presentation build() {
			return new Presentation(this.documentTarget, this.width, this.height, this.returnUrl, this.locale);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Presentation.PresentationBuilder(documentTarget=" + this.documentTarget + ", width=" + this.width + ", height=" + this.height + ", returnUrl=" + this.returnUrl + ", locale=" + this.locale + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Presentation.PresentationBuilder builder() {
		return new Presentation.PresentationBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getDocumentTarget() {
		return this.documentTarget;
	}

	@java.lang.SuppressWarnings("all")
	public int getWidth() {
		return this.width;
	}

	@java.lang.SuppressWarnings("all")
	public int getHeight() {
		return this.height;
	}

	@java.lang.SuppressWarnings("all")
	public String getReturnUrl() {
		return this.returnUrl;
	}

	@java.lang.SuppressWarnings("all")
	public String getLocale() {
		return this.locale;
	}

	@JsonProperty("document_target")
	@java.lang.SuppressWarnings("all")
	public void setDocumentTarget(final String documentTarget) {
		this.documentTarget = documentTarget;
	}

	@java.lang.SuppressWarnings("all")
	public void setWidth(final int width) {
		this.width = width;
	}

	@java.lang.SuppressWarnings("all")
	public void setHeight(final int height) {
		this.height = height;
	}

	@JsonProperty("return_url")
	@java.lang.SuppressWarnings("all")
	public void setReturnUrl(final String returnUrl) {
		this.returnUrl = returnUrl;
	}

	@JsonProperty("locale")
	@java.lang.SuppressWarnings("all")
	public void setLocale(final String locale) {
		this.locale = locale;
	}

	@java.lang.SuppressWarnings("all")
	public Presentation() {
	}

	@java.lang.SuppressWarnings("all")
	public Presentation(final String documentTarget, final int width, final int height, final String returnUrl, final String locale) {
		this.documentTarget = documentTarget;
		this.width = width;
		this.height = height;
		this.returnUrl = returnUrl;
		this.locale = locale;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Presentation(documentTarget=" + this.getDocumentTarget() + ", width=" + this.getWidth() + ", height=" + this.getHeight() + ", returnUrl=" + this.getReturnUrl() + ", locale=" + this.getLocale() + ")";
	}
}
