// Generated by delombok at Fri Jul 14 17:42:49 CEST 2023
package edu.uoc.lti.deeplink.content;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * @author Created by xaracil@uoc.edu
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Window {
	private String targetName;
	private int with;
	private int height;
	private String windowFeatures;


	@java.lang.SuppressWarnings("all")
	public static class WindowBuilder {
		@java.lang.SuppressWarnings("all")
		private String targetName;
		@java.lang.SuppressWarnings("all")
		private int with;
		@java.lang.SuppressWarnings("all")
		private int height;
		@java.lang.SuppressWarnings("all")
		private String windowFeatures;

		@java.lang.SuppressWarnings("all")
		WindowBuilder() {
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Window.WindowBuilder targetName(final String targetName) {
			this.targetName = targetName;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Window.WindowBuilder with(final int with) {
			this.with = with;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Window.WindowBuilder height(final int height) {
			this.height = height;
			return this;
		}

		/**
		 * @return {@code this}.
		 */
		@java.lang.SuppressWarnings("all")
		public Window.WindowBuilder windowFeatures(final String windowFeatures) {
			this.windowFeatures = windowFeatures;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		public Window build() {
			return new Window(this.targetName, this.with, this.height, this.windowFeatures);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "Window.WindowBuilder(targetName=" + this.targetName + ", with=" + this.with + ", height=" + this.height + ", windowFeatures=" + this.windowFeatures + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	public static Window.WindowBuilder builder() {
		return new Window.WindowBuilder();
	}

	@java.lang.SuppressWarnings("all")
	public String getTargetName() {
		return this.targetName;
	}

	@java.lang.SuppressWarnings("all")
	public int getWith() {
		return this.with;
	}

	@java.lang.SuppressWarnings("all")
	public int getHeight() {
		return this.height;
	}

	@java.lang.SuppressWarnings("all")
	public String getWindowFeatures() {
		return this.windowFeatures;
	}

	@java.lang.SuppressWarnings("all")
	public void setTargetName(final String targetName) {
		this.targetName = targetName;
	}

	@java.lang.SuppressWarnings("all")
	public void setWith(final int with) {
		this.with = with;
	}

	@java.lang.SuppressWarnings("all")
	public void setHeight(final int height) {
		this.height = height;
	}

	@java.lang.SuppressWarnings("all")
	public void setWindowFeatures(final String windowFeatures) {
		this.windowFeatures = windowFeatures;
	}

	@java.lang.SuppressWarnings("all")
	public Window() {
	}

	@java.lang.SuppressWarnings("all")
	public Window(final String targetName, final int with, final int height, final String windowFeatures) {
		this.targetName = targetName;
		this.with = with;
		this.height = height;
		this.windowFeatures = windowFeatures;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Window(targetName=" + this.getTargetName() + ", with=" + this.getWith() + ", height=" + this.getHeight() + ", windowFeatures=" + this.getWindowFeatures() + ")";
	}
}
